# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nextbus}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Greg"]
  s.date = %q{2010-02-18}
  s.description = %q{NextBus API client}
  s.email = %q{gsterndale@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".bundle/environment.rb",
     ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/nextbus.rb",
     "test/helper.rb",
     "test/test_nextbus.rb",
     "vendor/cache/columnize-0.3.1.gem",
     "vendor/cache/linecache-0.43.gem",
     "vendor/cache/mocha-0.9.8.gem",
     "vendor/cache/rake-0.8.7.gem",
     "vendor/cache/ruby-debug-0.10.3.gem",
     "vendor/cache/ruby-debug-base-0.10.3.gem"
  ]
  s.homepage = %q{http://github.com/gsterndale/nextbus}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{NextBus API client}
  s.test_files = [
    "test/helper.rb",
     "test/test_nextbus.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

